import os
from groq import Groq

def get_groq_score(text: str) -> float:
    """
    Sends text to Groq LLM and returns a float between 0.0 and 1.0
    representing the likelihood that the text is AI-generated.
    1.0 = definitely AI, 0.0 = definitely human.
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return a single decimal number between 0.0 and 1.0:
- 1.0 means you are certain the text was AI-generated
- 0.0 means you are certain the text was written by a human
- 0.5 means you are completely uncertain

Return ONLY the number. No explanation, no punctuation, no extra text.

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1
    )

    raw = response.choices[0].message.content.strip()

    try:
        score = float(raw)
        return max(0.0, min(1.0, score))
    except ValueError:
        return 0.5